### ISSUE TITLE
*_temp* variables not found

### ISSUE THREAD

**Issue by Leevisir** [OpenSourceAP/CrossSection#45] opened 2021-07-11 16:04 UTC
Hi,

I tried to run the Stata code but encountered some problems. I had these errors of variables not found: "*_temp* not found" for some variables. They are sd10_tempEarnings, mean6_temp, and sd60_tempEpsDiff. I got stuck here and failed to solve it. Could anyone please help? 

If this issue is not actually an issue, please accept my apology. I am very new to Stata programming.

Thanks

**Comment by tomz23** [comment] 2021-07-12 08:16
Can you indicate in which files you received the error?

**Comment by chenandrewy** [comment] 2021-10-04 20:48
It seems that sd10_tempEarnings is found in Placebos/EarningsSmoothness.do.  I haven't taken a look to check that this runs yet.

**Comment by tomz23** [comment] 2022-02-14 15:00
I ran two files that generate variables named as specified (`Placebos/EarningsSmoothness.do` and `Predictors/ZZ1_ResidualMomentum6m_ResidualMomentum`) but was not able to reproduce the error. 
My guess is that it's related to a missing installation of the `asreg` and `asrol` commands.

As I can't reproduce the error and no further information was provided, I'm closing this issue.

**Closed by tomz23** 2022-02-14 15:00 UTC
Labels: check and fix
